version: "3.4"

services:
  catalogdb:
    image: mongo # Образ mongo должен быть извлечен из DockerHub
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
